# This is an example of what an '_config.yml' file should look like
# when using jekyll-shell-theme. You should use this as a guide or
# just copy+paste it and modify some of the content to begin with.

title: Portfolio
linkedin: yyy
description: >- # this means to ignore newlines until "baseurl:"
  Portfolio contendo mais detalhes dos projetos e da minah experiência.
baseurl: "/egodev2.github.io"  # the subpath of your site
github_username:  egodev2

# Required plugins for the theme to work properly
plugins:
  - jekyll-remote-theme
  - jemoji

# Including jekyll-shell-theme using the jekyll-remote-theme plugin
remote_theme: tareqdandachi/jekyll-shell-theme

sass:
  style: compressed

highlighter: rouge #selecting the highlighter, default is rouge

header_pages:
  - index.md
  - about.md
  - a-third-page.md

# controls how big the shell and font looks
font-size: small # options: [small] or [large]
